
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Cezarino Hora
 */
public class Form1 extends javax.swing.JFrame {

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimpar = new javax.swing.JButton();
        txtvalor02 = new javax.swing.JTextField();
        txtvalor01 = new javax.swing.JTextField();
        lblProjetoSoma = new javax.swing.JLabel();
        lblValor01 = new javax.swing.JLabel();
        lblValor02 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Soma - By Cezar Hora Dev");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpar.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 384, 174, 64));
        getContentPane().add(txtvalor02, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 200, 220, 53));

        txtvalor01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalor01ActionPerformed(evt);
            }
        });
        getContentPane().add(txtvalor01, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 220, 46));

        lblProjetoSoma.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblProjetoSoma.setText("Projeto Soma");
        getContentPane().add(lblProjetoSoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        lblValor01.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblValor01.setText("Valor 01:");
        getContentPane().add(lblValor01, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 145, -1, -1));

        lblValor02.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblValor02.setText("Valor 02:");
        getContentPane().add(lblValor02, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 212, -1, -1));

        lblTotal.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblTotal.setText("Total:");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 283, -1, -1));

        txttotal.setEditable(false);
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 271, 220, 53));

        btnCalcular.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 384, 174, 64));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // Botão Limpar
        txtvalor01.setText(null);
        txtvalor02.setText(null);
        txttotal.setText(null);
        txtvalor01.requestFocus();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtvalor01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalor01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalor01ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        /// Botão Calcular
        // 1 passo - Entrada - Receber os valores do usuário
        double v1, v2, total;
        v1 = Double.parseDouble(txtvalor01.getText());
        v2 = Double.parseDouble(txtvalor02.getText());
        
        // 2 passo - Processamento - cálculo
        total = v1 + v2;
         
        // 3 passo - Saída - Exibir o resultado
        txttotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel lblProjetoSoma;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValor01;
    private javax.swing.JLabel lblValor02;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtvalor01;
    private javax.swing.JTextField txtvalor02;
    // End of variables declaration//GEN-END:variables
}
